$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: md-triton

model: azureml:moondream_triton:3

instance_type: Standard_NC8as_T4_v3
instance_count: 1


liveness_probe:
  initial_delay: 10
  period: 10
  timeout: 2
  failure_threshold: 30
  success_threshold: 1

readiness_probe:
  initial_delay: 10
  period: 10
  timeout: 2
  failure_threshold: 30
  success_threshold: 1

request_settings:
  request_timeout_ms: 180000
  max_concurrent_requests_per_instance: 500
  max_queue_wait_ms: 10000
